# Generated by Django 3.0.8 on 2020-10-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=150)),
                ('videolink', models.CharField(max_length=150)),
                ('videodisc', models.CharField(max_length=500)),
                ('caption', models.CharField(max_length=10000)),
                ('thumbnail_image', models.ImageField(upload_to='thumbnail/')),
            ],
        ),
    ]
