# Generated by Django 3.0.8 on 2020-10-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_youtubevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='caption',
        ),
    ]
