# Generated by Django 3.0.8 on 2020-10-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_remove_youtubevideo_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(default='No thumbnail', upload_to='thumbnail/'),
        ),
    ]
